package measures_of_central_tendency_app;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MOHAMMED
 */
public class Home_Page_Ibrahim_Mohammed extends javax.swing.JFrame {

    /**
     * Creates new form Main_1
     */
    public Home_Page_Ibrahim_Mohammed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ibrahim Mohammed ITE C \n0249714502\n");
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/men.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("Welcome To Statistics Hub");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu2.setBackground(new java.awt.Color(255, 51, 51));
        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/folder.png"))); // NOI18N
        jMenu2.setText("File");
        jMenu2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/exit.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 51, 51));
        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/add.png"))); // NOI18N
        jMenu3.setText("Mean");
        jMenu3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem2.setText("Sample Mean");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem3.setText("Frequency Distrubution");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem4.setText("Weighted Mean");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 51, 51));
        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/edit.png"))); // NOI18N
        jMenu4.setText("Mode");
        jMenu4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem5.setText("Sample Values");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem6.setText("Frequency Distrubution");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 51, 51));
        jMenu5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/job.png"))); // NOI18N
        jMenu5.setText("Median");
        jMenu5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem7.setText("Sample Values");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem8.setText("Grouped Data");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(255, 51, 51));
        jMenu6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/edit.png"))); // NOI18N
        jMenu6.setText("Measures Of Dispersion");
        jMenu6.setFocusable(false);
        jMenu6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem9.setText("Range");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem11.setText("Variance");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem12.setText("Standard Deviation");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem14.setText("Coefficience Of Variance");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuItem13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem13.setText("Quartile Deviation");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem10.setText("M.D For Sample Values");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(255, 51, 51));
        jMenu7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/measures_of_central_tendency_app/Pics/addemployee.png"))); // NOI18N
        jMenu7.setText("Developers Info");
        jMenu7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem15.setText("View Details");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        medianForGroupedData mfgd = new medianForGroupedData();
        
          mfgd.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        varianceForm vForm = new varianceForm();
       vForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       standardDeviationForm SDform = new standardDeviationForm(); 
       
       SDform.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
      
        
        
        developersList list = new developersList();
        list.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       
         
        
        Scanner input = new Scanner(System.in);
        
        ArrayList<Double> list = new ArrayList<>();
        int size;
        double range;
        double min;
        double max;
      size= Integer.parseInt(JOptionPane.showInputDialog(null,"How many numbers ? : ")) ; 
        
      for(int counter=0; counter<size; counter++)
      {
            list.add(Double.parseDouble(JOptionPane.showInputDialog("Enter the Number :  "+(counter+1))));  
       
      }
      
      JOptionPane.showMessageDialog(null,"Your numbers are  : "+ list);
      
     
     
     
    
    
      min= Collections.min(list);
      max=  Collections.max(list);
      
      range = max-min;
      
      JOptionPane.showMessageDialog(null, "The range of your numbers is :  " + range);
    

        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        meanDeviationForSampleValues mdfsv = new meanDeviationForSampleValues();
        mdfsv.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      Scanner input = new Scanner(System.in);
       
       double size;
       ArrayList<Integer> list = new ArrayList();
       
       double median=0;
       
       size= Integer.parseInt(JOptionPane.showInputDialog(null,"How many numbers are they? ")); 
       
       
        for(int counter=0; counter<size; counter++)
        {
             list.add(Integer.parseInt(JOptionPane.showInputDialog("Enter the Number :  "+(counter+1)))); 
              
        }
        
        
        JOptionPane.showMessageDialog(null, "Your numbers are :"+ list);
        
        Collections.sort(list);
        
        
         size = Math.ceil(size/2);
         
       if(size%2==0)
       {
            Double m = size;
            int medi = m.intValue();
        
         
            double firstMidValue = list.get(medi-1);
            double secondMidValue=list.get(medi);
     
         
            median = ((firstMidValue)+(secondMidValue))/2;
        
                             
     
         JOptionPane.showMessageDialog(null, " The median is : "+ median );
       }
       else
       {
              Double m = size;
         
              int medi = m.intValue();
         
               JOptionPane.showMessageDialog(null, " The median is : "+ list.get(medi));  
       }
        
        

          
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        coefficientOfVariationForm cofForm = new coefficientOfVariationForm();
        cofForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Warning worning = new Warning();
        
        worning.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
    Scanner input = new Scanner(System.in);
    
    
    
    int size= 0;
    
   size = Integer.parseInt(JOptionPane.showInputDialog(null,"How many are your numbers? ")) ;

    
   
    
    int[] dataSet =  new int[size];
    
    for(int num =0; num<size; num++)
    {
        
        dataSet[num]+=Integer.parseInt( JOptionPane.showInputDialog(null,"Enter the numbers : "+ (num+1)));
         
    }
    
        
    int maxNumber = -1;
    int maxAppearance = -1;
    for(int i = 0; i<dataSet.length; i++ )
    {
       
         int count = 0;
         
         for(int j=0; j<dataSet.length; j++)
            {
             
            if(dataSet[i] == dataSet[j])
                count++;
            
          
            }
           if(count>maxAppearance)
           {
                maxNumber = dataSet[i];
                maxAppearance=count; 
            
           }
          
         
    }
    
     JOptionPane.showMessageDialog(null,"The mode is "+ maxNumber );   
    

       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      
     SampleMean mean = new SampleMean();
     mean.setVisible(true);
            
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      WeightedMeanForm WMform = new WeightedMeanForm();
      WMform.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       frequencyDistributionForm fForm = new  frequencyDistributionForm();
      
      fForm.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       modeForFrequencyDistribution mffd = new modeForFrequencyDistribution();
       mffd.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Ibrahim_Mohammed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Ibrahim_Mohammed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Ibrahim_Mohammed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Ibrahim_Mohammed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new Home_Page_Ibrahim_Mohammed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
